#!/bin/sh
# WARNING: REQUIRES /bin/sh
#
# Post install configuration for Chef Development Kit
#

PROGNAME=`basename $0`
INSTALLER_DIR=/opt/hem
USAGE="usage: $0"

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

is_smartos()
{
  uname -v | grep "^joyent" 2>&1 >/dev/null
}

if is_smartos; then
    PREFIX="/opt/local"
else
    PREFIX="/usr"
fi

# We test for the presence of /usr/bin/chef-client to know if this script succeeds,
# so chef-client must appear as the last item here.
binaries="hem"

# rm -f before ln -sf is required for solaris 9
for binary in $binaries; do
  rm -f $PREFIX/bin/$binary
done

for binary in $binaries; do
  ln -sf $INSTALLER_DIR/bin/$binary $PREFIX/bin || error_exit "Cannot link $binary to $PREFIX/bin"
done

# pre-populate user gems with cached ones from hem
mkdir -p ~/.hem/gems/
cp -R $INSTALLER_DIR/embedded/lib/ruby/gems/* ~/.hem/gems/ruby/
USER=$($INSTALLER_DIR/embedded/bin/ruby -r etc -e 'print Etc.getpwuid(File.stat(File.expand_path("~/")).uid).name')
chown -R $USER ~/.hem/gems

# Ensure all files/directories in $INSTALLER_DIR are owned by root. This
# has been fixed on new installs but upgrades from old installs need to
# be manually fixed.
chown -Rh 0:0 $INSTALLER_DIR

echo "Thank you for installing Hem!"

exit 0
